name: Push to Replicate

on:
  push:
    branches:
      - main
      - segmind-ssd
  workflow_dispatch:

jobs:
  push:
    runs-on: 4-core-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Build and Push
        run: |
          cog build -t r8.im/vantilator2000/pbr-texture-gen
          cog push r8.im/vantilator2000/pbr-texture-gen
